amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: order_service
  password: 123456
mysql:
  username: root
  password: 9655
  schema: order_service
  url: localhost:3306

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2