spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:order_service_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enabled: true
      path: /h2